### ISSUE TITLE
Option for Transfer Learning

### ISSUE THREAD

**Issue by shan18** [shan18/Flash#6]
While training the model, give the user an option to pre-train their models on the following datasets:
- ImageNet
- CIFAR100

This milestone will be done in two steps:
1. Updating the training server code (the cifar100 model checkpoints will be present in the EC2 instance itself) [Handled by @rvk007]
2. Showing the configuration options in the frontend [Handled by @shan18]

**Comment by shan18** [comment]
Changes from frontend and lambda completed in b11579e9f77bb34ad3c323ebce2ac2e49f2da881

**Comment by rvk007** [comment]
Made changes from backend for transfer learning in 9ed8b10b6014cc5252c22fec6b282fd5ecbdd9fb
