### ISSUE TITLE
Add model choices

### ISSUE THREAD

**Issue by shan18** [shan18/Flash#7]
In the training module, add more model choices like `ResNet18` and other models which can fit into AWS Lambda.

Backend code will be handled by @rvk007 and frontend will be updated by @shan18

**Comment by shan18** [comment]
Frontend updated in 7092a5ed5359c04e4d2bef5c42d2a11622fb68bc

**Comment by rvk007** [comment]
Completed backed changes in 3dfd3c3f85cc6752959d9d7007b3b2bb27d28586
