### ISSUE TITLE
LR Schedulers

### ISSUE THREAD

**Issue by shan18** [shan18/Flash#8]
Give user the option to train the model with more LR schedulers such as
- One Cycle Policy
- StepLR

Will have 2 milestones
- Update training server code [Handled by @rvk007]
- Show changes in frontend [Handled by @shan18]

**Comment by shan18** [comment]
Frontend updated in 7092a5ed5359c04e4d2bef5c42d2a11622fb68bc

**Comment by rvk007** [comment]
Completed backend changes in 3dfd3c3f85cc6752959d9d7007b3b2bb27d28586
